import { I_PoptartConfig } from '.';

export const defaultConfig: I_PoptartConfig = {
	colors: {
		success: '#229645',
		error: '#e71b44',
		warning: '#ffdc2e',
		info: '#1FA2FF',
		textLight: '#f9f9f9',
		textDark: '#171717',
	},
	styleOverrides: {
		container: {},
		poptart: {},
		progressBar: {},
		alertContainer: {},
		alert: {},
	},
	defaultAlign: 'br',
	defaultType: 'info',
	defaultDuration: 5000,
	defaultWidth: '450px',
	defaultAnimation: 'bounceIn',
	defaultAnimationDuration: 0.6,
	fontSize: 16,
	iconSizeFactor: 2.5,
	progressBar: {
		lightColor: '#D6D6D6',
		darkColor: '#454545',
		height: 5,
	},
	contrastThreshold: 0.32,
	paddingX: 20,
	paddingY: 16,
	zIndex: 10,
	alerts: {
		defaultWidth: '800px',
		paddingX: 30,
		paddingY: 26,
		borderRadius: 10,
		defaultType: 'info',
		defaultBackgroundColor: '#ffffff',
		defaultFontColor: '#000',
		defaultFontSize: 20,
		defaultTitleFontSize: 28,
		iconSizeFactor: 2,
		borderWidth: 3,
		defaultConfirmButtonColor: '#2d2d2d',
		defaultCancelButtonColor: '#6B6B6B',
		defaultConfirmButtonLabel: 'Ok',
		defaultCancelButtonLabel: 'Cancel',
		defaultShowCancelButton: false,
		defaultShowConfirmButton: true,
		defaultAnimation: 'slideFromBottom',
		defaultAnimationDuration: 0.25,
		allowClickOffDismissal: true,
		input: {
			backgroundColor: '#fcfcfcac',
			fontColor: '#000',
			borderRadius: 5,
			borderWidth: 1,
			paddingX: 10,
			paddingY: 8,
			maxWidth: '70%',
			errorFeedbackColor: '#d12c2c',
			placeholderColor: '#a0a0a0',
		},
	},
};
