import { I_PoptartConfig } from '.';

export const defaultConfig: I_PoptartConfig = {
	colors: {
		success: '#1a7e38',
		error: '#e4002d',
		warning: '#e4bf00',
		info: '#1FA2FF',
		textLight: '#E8E8E8',
		textDark: '#1F1F1F',
	},
	styleOverrides: {
		container: {},
		poptart: {},
		progressBar: {},
		alertContainer: {},
		alert: {},
	},
	defaultAlign: 'br',
	defaultType: 'info',
	defaultDuration: 5000,
	defaultWidth: '450px',
	defaultAnimation: 'bounceIn',
	defaultAnimationDuration: 0.6,
	fontSize: 16,
	iconSizeFactor: 2.5,
	progressBar: {
		lightColor: '#D6D6D6',
		darkColor: '#454545',
		height: 5,
	},
	contrastThreshold: 0.32,
	paddingX: 20,
	paddingY: 16,
	zIndex: 10,
	alerts: {
		defaultWidth: '800px',
		paddingX: 30,
		paddingY: 26,
		borderRadius: 10,
		defaultType: 'info',
		defaultBackgroundColor: '#F5F5F5',
		defaultFontColor: '#000',
		defaultFontSize: 20,
		defaultTitleFontSize: 28,
		iconSizeFactor: 2,
		borderWidth: 8,
		defaultConfirmButtonColor: '#1A1A1A',
		defaultCancelButtonColor: '#6B6B6B',
		defaultConfirmButtonLabel: 'Ok',
		defaultCancelButtonLabel: 'Cancel',
		defaultShowCancelButton: false,
		defaultShowConfirmButton: true,
		defaultAnimation: 'slideFromBottom',
		defaultAnimationDuration: 0.25,
		allowClickOffDismissal: true,
	},
};
